spring:
  application:
    name: cogniarium-backend

  # Default active profile is 'dev' unless specified otherwise at runtime
  profiles:
    active: dev

webclient:
  max-in-memory-size: 16MB

# Hugging Face Configuration
huggingface:
  api:
    url: http://localhost:8000/analyze
    timeout: 60000

# Backend Configuration
backend:
  base-url: ${BACKEND_BASE_URL:http://host.docker.internal:8080}
  callbacks:
    sentiment: /api/callbacks/sentiment
    title: /api/callbacks/title
    summary: /api/callbacks/summary
